PUT file:///Path.json @$stage;
CREATE OR REPLACE TRANSIENT TABLE DATABASE.SCHEMA.TABLE_NAME AS
SELECT
    $1:FLAG::STRING as FLAG,
    $1:UNIT::STRING as UNIT,
    $1:NAME::STRING as NAME
FROM @$stage/FILE_NAME.json (FILE_FORMAT => JSON_FORMAT);