CREATE OR REPLACE TEMP STAGE $stage
COMMENT = 'FILES FROM DIFFERENTS API';

CREATE TEMP FILE FORMAT IF NOT EXISTS PARQUET_FORMAT
COMPRESSION = AUTO
TYPE = 'PARQUET';

CREATE TEMP FILE FORMAT IF NOT EXISTS JSON_FORMAT
TYPE = 'JSON'
COMPRESSION = AUTO
STRIP_OUTER_ARRAY = TRUE;