COPY INTO @$stage/FILE_NAME.parquet
FROM (
    SELECT * FROM TABLE
)    
FILE_FORMAT = (TYPE = PARQUET)
HEADER = TRUE
MAX_FILE_SIZE = 900000000
SINGLE = TRUE;
GET @$stage/FILE_NAME.parquet file://PATH;